name: 'plants_analytics'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  plants_analytics:
    base:
      +materialized: view
    intermediate:
      +materialized: view
    analytics:
      +materialized: table